[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
darkpool = "2pdQQB9pMDbM7VFYPwwFs2gPC1GMsHwYHavg6Dzh33K4"

[programs.devnet]
darkpool = "95XwPFvP6znDJN2XS4JRp29NjUNGEKDAmCRfKaZEzNfw"

[programs.mainnet]
darkpool = "2pdQQB9pMDbM7VFYPwwFs2gPC1GMsHwYHavg6Dzh33K4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[build]
solana_version = "1.18.26"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/darkpool"]

